config/routes.rb
Rails.application.routes.draw do
  resources :flats
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
	belongs_to :user
	mount_uploader :photo, PhotoUploader

	geocoded_by :address
	after_validation :geocode, if: :will_save_change_to_address?

	include PgSearch::Model
		pg_search_scope :search_by_name_and_description_and_address,
		against: [ :name, :description, :address ], using: {
		tsearch: { prefix: true }
	}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :flats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

  	include Pundit
	# Pundit: white-list approach.
	after_action :verify_authorized, except: :index, unless: :skip_pundit?
	after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
	
	# Uncomment when you *really understand* Pundit!
	# rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
	# def user_not_authorized
	# flash[:alert] = "You are not authorized to perform this action."
	# redirect_to(root_path)
	# end

	private
		def skip_pundit?
			devise_controller? || params[:controller] =~/(^(rails_)?admin)|(^pages$)/
		end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @flats = policy_scope(Flat).search_by_name_and_description_and_address(params[:query])
    else
      @flats = policy_scope(Flat)
    end
  end

  def show
    @center = [@flat.longitude, @flat.latitude]
    @marker = [{latitude: @flat.latitude, longitude: @flat.longitude}]
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def edit
  end

  def create
    @flat = Flat.new(flat_params)
    authorize @flat
    @flat.user = current_user

    if @flat.save
      redirect_to @flat, notice: 'Flat was successfully created.'
    else
      render :new
    end
  end

  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_url, notice: 'Flat was successfully destroyed.'
  end

  private
    def set_flat
      @flat = Flat.find(params[:id])
      authorize @flat
    end

    def flat_params
      params.require(:flat).permit(:name, :description, :address, :photo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  	if params[:query].present?
      @flats = policy_scope(Flat).search_by_name_and_description_and_address(params[:query])
    else
      @flats = policy_scope(Flat)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/_flat_card.html.erb
<div class="flat_card">
	<%= link_to flat_path(flat) do %>
	  	<%= cl_image_tag flat.photo, width: 500, height: 200, crop: :fill %>
	  	<div class="details">
			<h1><%= flat.name %></h1>
			<p><%= flat.description %></p>
		</div>
	<% end %>
</div>

app/views/flats/_flat_listing.html.erb
<div class="flat_listing">
	<%= form_tag flats_path, method: :get, class:"w-100 form-inline mb-4" do %>
		<%= text_field_tag :query, params[:query], class: "form-control form-control-lg flex-grow-1 flex-shrink-1", style:"width: 100px !important;", placeholder: "Find a flat" %>
		<%= submit_tag "Search", class: "btn btn-lg btn-primary" %>
	<% end %>
    <div class="row">
        <% flats.each do |flat| %>
        <div class="col-sm-6 col-lg-4">
            <%= render "flats/flat_card", :flat => flat %>
        </div>
        <% end %>
    </div>
</div>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address %>

    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary btn-pill" %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<div class="container py-4">
	<h1>Edit <%= @flat.name %></h1>
	<h4>Hosted by <%= @flat.user.email %></h4>

	<%= render 'form', flat: @flat %>
	<%= link_to 'Back', @flat, class: "btn btn-secondary my-4 btn-pill" %>
</div>

app/views/flats/index.html.erb
<%= render "flat_listing", :flats => @flats %>

app/views/flats/new.html.erb
<div class="container py-4">
	<h1>Host a flat</h1>

	<%= render 'form', flat: @flat %>

	<%= link_to 'Back', flats_path, class: "btn btn-secondary my-4 btn-pill" %>
</div>

app/views/flats/show.html.erb
<div class="container py-4">
    <div class="flat_details">
        <%= cl_image_tag @flat.photo, width: 800, height: 450, crop: :fill %>
        <div class="details">
            <h1>
                <%= @flat.name %>
            </h1>
            <p>
                <%= @flat.description %>
            </p>
            <h4>Address</h4>
            <p>
                <%= @flat.address %>
            </p>
            <h4>Host</h4>
            <p>
                <%= @flat.user.email %>
            </p>
        </div>
        <div id="map" style="width: 100%; height: 600px;" data-center="<%= @center.to_json %>" data-markers="<%= @marker.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
    </div>
    <% if policy(@flat).edit? %>
    <%= link_to 'Edit Listing', edit_flat_path(@flat), class:"btn btn-secondary btn-pill mr-4" %>
    <% end %>
    <%= link_to 'Back', flats_path, class:"btn btn-primary btn-pill" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PrefaceBnB</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home_page">
	
	<section class="hero">
		<canvas class="bubbly"></canvas>
		<div class="foreground">
			<%= image_tag "shared/logo.png", alt: "Logo" %>
			<h4>a coder friendly alternative for BnB</h4>
		</div>
	</section>

	<section class="listing">
		<%= render "flats/flat_listing", :flats => @flats %>
	</section>
	
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-dark navbar-preface">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "shared/logo.png" %>
    <h2>PrefaceBnB</h2>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "View listing", flats_path, class: "nav-link" %>
        </li>
        <% if policy(Flat).create? %>
          <li class="nav-item">
            <%= link_to "Host a flat", new_flat_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <a ref="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.email %></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>